/* ═══════════════════════════════════════════════════
   Vercel Serverless Function — يخدم config.js عند النشر
   ═══════════════════════════════════════════════════
   config.js مستثنى من git (لأسباب أمنية)، لذلك لا يصل إلى Vercel.
   هذه الدالة تولّده من متغيرات بيئة Vercel:
     SUPABASE_URL
     SUPABASE_ANON_KEY
   يُعيد توجيه /config.js إلى هذه الدالة عبر vercel.json.
   ═══════════════════════════════════════════════════ */

module.exports = function (req, res) {
    var url = String(process.env.SUPABASE_URL || '').trim();
    var anonKey = String(process.env.SUPABASE_ANON_KEY || '').trim();
    res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
    res.setHeader('Cache-Control', 'no-store');
    res.send(
        '/* Auto-generated by Vercel from env vars */\n' +
        'window.SUPABASE_URL = ' + JSON.stringify(url) + ';\n' +
        'window.SUPABASE_ANON_KEY = ' + JSON.stringify(anonKey) + ';\n'
    );
};
